### ISSUE TITLE
Infograph / Graphic Circular

### ISSUE THREAD

**Issue by svenblum** [arvdsar/node-red-contrib-complicated#1]
Infograph / Graphic Circular isn't supported.

maybee add
`            <option value="graphicCircular">graphicCircular</option>`

to line 40 in complicated.html

ty very much!

**Comment by arvdsar** [comment]
Thanks for the suggestion. I’ll try to have a look this weekend!

**Comment by arvdsar** [comment]
@svenblum I have added your suggestion and published the package to npmjs.org.
It should be visible in a couple of hours.
